apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: studio-app-preprod
  namespace: argocd
  annotations:
    harness.io/skip-validation: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/mahergzam/harness-gitops-hydration.git
    targetRevision: envs/preprod   # Argo CD watches this branch
    path:.                         # all files in root of branch
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app-preprod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
