---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: preprod-test-app
  namespace: test-app-preprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: nginx:1.25.0
        name: test-app
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
