---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: harness-gitops
    app.kubernetes.io/name: test-app
  name: preprod-test-app-stable
  namespace: test-app-preprod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/managed-by: harness-gitops
    app.kubernetes.io/name: test-app
  type: ClusterIP
