apiVersion: v1
kind: Service
metadata:
  name: test-app-stable
  labels:
    app.kubernetes.io/name: test-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: test-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
