---
apiVersion: v1
kind: Service
metadata:
  name: preprod-test-app
  namespace: test-app-preprod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-app
  type: ClusterIP
